# Generated by Django 4.2.5 on 2024-07-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_product_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="amount", field=models.IntegerField(default=0),
        ),
    ]
