# Generated by Django 4.2.5 on 2024-07-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact_phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.IntegerField(
                        max_length=11, verbose_name="شماره ارتباط با ما"
                    ),
                ),
            ],
            options={
                "verbose_name": "شماره تماس",
                "verbose_name_plural": "شماره های تماس",
            },
        ),
    ]
